In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
pd.__version__

'2.2.1'

In [ ]:
pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
pd.__version__

'2.2.1'

#Read the csv file

In [ ]:
data=pd.read_csv('fraudTest.csv')
data

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497.0,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1.371817e+09,33.986391,-81.200714,0.0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302.0,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1.371817e+09,39.450498,-109.960431,0.0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496.0,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1.371817e+09,40.495810,-74.196111,0.0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767.0,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1.371817e+09,28.812398,-80.883061,0.0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126.0,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1.371817e+09,44.959148,-85.884734,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62228,62228,2020-07-13 00:12:23,3595192916105588,"fraud_Towne, Walker and Borer",grocery_net,38.20,Dustin,Roberts,M,3283 James Station,...,35.0583,-79.0080,238602.0,"Scientist, research (maths)",1993-05-14,1ce2c8a6e4d54bd43a1cd8714f97ae81,1.373674e+09,35.301335,-78.691145,0.0
62229,62229,2020-07-13 00:14:14,630441765090,fraud_Mraz-Herzog,gas_transport,64.99,Susan,Washington,F,759 Erin Mount Suite 956,...,31.9571,-98.9656,1791.0,Corporate investment banker,1965-07-26,f27925fedbe6def9b14bf707e20c31eb,1.373674e+09,31.241113,-99.596277,0.0
62230,62230,2020-07-13 00:14:14,30153452207526,fraud_Leannon-Ward,food_dining,16.56,Robin,Smith,F,0537 Margaret Common Suite 526,...,31.8287,-99.4270,5908.0,Radio producer,1962-04-05,f7800a6eda535c5f43a7ecf27f0ace0b,1.373674e+09,30.967988,-99.167286,0.0
62231,62231,2020-07-13 00:14:56,213102873001603,"fraud_Parisian, Schiller and Altenwerth",misc_net,1.37,Joanne,Padilla,F,477 Alejandro Knolls Suite 828,...,43.7857,-124.1437,260.0,"Engineer, maintenance",1956-09-01,34a2a064febff68e2751cf8887b7632c,1.373674e+09,42.984200,-123.658778,0.0
62232,62232,2020-07-13 00:15:17,30518206766474,fraud_Parisian and,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62233 entries, 0 to 62232
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             62233 non-null  int64
 1   trans_date_trans_time  62233 non-null  object
 2   cc_num                 62233 non-null  int64
 3   merchant               62233 non-null  object
 4   category               62232 non-null  object
 5   amt                    62232 non-null  float64
 6   first                  62232 non-null  object
 7   last                   62232 non-null  object
 8   gender                 62232 non-null  object
 9   street                 62232 non-null  object
 10  city                   62232 non-null  object
 11  state                  62232 non-null  object
 12  zip                    62232 non-null  float64
 13  lat                    62232 non-null  float64
 14  long                   62232 non-null  float64
 15  city_pop               62232 non-null  float64
 16  job                    62232 non-null  object
 17  dob                    62232 non-null  object
 18  trans_num              62232 non-null  object
 19  unix_time              62232 non-null  float64
 20  merch_lat              62232 non-null  float64
 21  merch_long             62232 non-null  float64
 22  is_fraud               62232 non-null  float64
dtypes: float64(9), int64(2), object(12)
memory usage: 10.9+ MB

In [ ]:
data.duplicated().sum()

0

In [ ]:
data.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 1
amt                      1
first                    1
last                     1
gender                   1
street                   1
city                     1
state                    1
zip                      1
lat                      1
long                     1
city_pop                 1
job                      1
dob                      1
trans_num                1
unix_time                1
merch_lat                1
merch_long               1
is_fraud                 1
dtype: int64

In [ ]:
data['city_pop'].fillna(data['city_pop'].median(), inplace=True)
data['unix_time'].fillna(data['unix_time'].median(), inplace=True)
data['merch_lat'].fillna(data['merch_lat'].median(), inplace=True)
data['merch_long'].fillna(data['merch_long'].median(), inplace=True)
data['is_fraud'].fillna(0, inplace=True)

<ipython-input-11-fec5d3d0a6d9>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['city_pop'].fillna(data['city_pop'].median(), inplace=True)
<ipython-input-11-fec5d3d0a6d9>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['unix_time'].fillna(data['unix_time'].median(), inplace=True)
<ipython-input-11-fec5d3d0a6d9>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['merch_lat'].fillna(data['merch_lat'].median(), inplace=True)
<ipython-input-11-fec5d3d0a6d9>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['merch_long'].fillna(data['merch_long'].median(), inplace=True)
<ipython-input-11-fec5d3d0a6d9>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['is_fraud'].fillna(0, inplace=True)

In [ ]:
data.dropna(subset=['unix_time', 'merch_lat', 'merch_long', 'is_fraud'], inplace=True)

In [ ]:
missing_values = data.isnull().sum()
print(missing_values)

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 1
amt                      1
first                    1
last                     1
gender                   1
street                   1
city                     1
state                    1
zip                      1
lat                      1
long                     1
city_pop                 0
job                      1
dob                      1
trans_num                1
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [ ]:

data.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497.0,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1.371817e+09,33.986391,-81.200714,0.0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302.0,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1.371817e+09,39.450498,-109.960431,0.0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496.0,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1.371817e+09,40.495810,-74.196111,0.0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767.0,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1.371817e+09,28.812398,-80.883061,0.0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126.0,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1.371817e+09,44.959148,-85.884734,0.0

In [ ]:
data.tail()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
62228,62228,2020-07-13 00:12:23,3595192916105588,"fraud_Towne, Walker and Borer",grocery_net,38.20,Dustin,Roberts,M,3283 James Station,...,35.0583,-79.0080,238602.0,"Scientist, research (maths)",1993-05-14,1ce2c8a6e4d54bd43a1cd8714f97ae81,1.373674e+09,35.301335,-78.691145,0.0
62229,62229,2020-07-13 00:14:14,630441765090,fraud_Mraz-Herzog,gas_transport,64.99,Susan,Washington,F,759 Erin Mount Suite 956,...,31.9571,-98.9656,1791.0,Corporate investment banker,1965-07-26,f27925fedbe6def9b14bf707e20c31eb,1.373674e+09,31.241113,-99.596277,0.0
62230,62230,2020-07-13 00:14:14,30153452207526,fraud_Leannon-Ward,food_dining,16.56,Robin,Smith,F,0537 Margaret Common Suite 526,...,31.8287,-99.4270,5908.0,Radio producer,1962-04-05,f7800a6eda535c5f43a7ecf27f0ace0b,1.373674e+09,30.967988,-99.167286,0.0
62231,62231,2020-07-13 00:14:56,213102873001603,"fraud_Parisian, Schiller and Altenwerth",misc_net,1.37,Joanne,Padilla,F,477 Alejandro Knolls Suite 828,...,43.7857,-124.1437,260.0,"Engineer, maintenance",1956-09-01,34a2a064febff68e2751cf8887b7632c,1.373674e+09,42.984200,-123.658778,0.0
62232,62232,2020-07-13 00:15:17,30518206766474,fraud_Parisian and,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2435.0,NaN,NaN,NaN,1.372693e+09,39.376194,-87.365683,0.0

In [ ]:
data.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [ ]:
data['is_fraud'].unique()

array([0., 1.])

In [ ]:
data['is_fraud']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
62228    0.0
62229    0.0
62230    0.0
62231    0.0
62232    0.0
Name: is_fraud, Length: 62233, dtype: float64

In [ ]:
data["is_fraud"].fillna(1, inplace = True)  # removing nan value by using fillna()method

In [ ]:
data['is_fraud'].unique()  #after removing nan values

array([0., 1.])

In [ ]:
df = data.drop('Unnamed: 0', axis=1)

In [ ]:
df.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud'],
      dtype='object')

In [ ]:
df['cc_num'],cc_name=pd.factorize(data['cc_num'])
print(cc_name)

Index([   2291163933867244,    3573030041201292,    3598215285024754,
          3591919803438423,    3526826139003047,      30407675418785,
           213180742685905,    3589289942931264,    3596357274378601,
          3546897637165774,
       ...
       4358137750029944984,     180098888332620,    3531606252458308,
            30373802285317,     377834944388609,    6526955903501879,
             4026222041577,    4682744518117239,    3540416671210051,
              503851367360],
      dtype='int64', length=911)

In [ ]:
data['category'],category_name=pd.factorize(data['category'])
print(category_name)

Index(['personal_care', 'health_fitness', 'misc_pos', 'travel', 'kids_pets',
       'shopping_pos', 'food_dining', 'home', 'entertainment', 'shopping_net',
       'misc_net', 'grocery_pos', 'gas_transport', 'grocery_net'],
      dtype='object')

In [ ]:
df['trans_date_trans_time'],time_name=pd.factorize(data['trans_date_trans_time'])
print(time_name)

Index(['2020-06-21 12:14:25', '2020-06-21 12:14:33', '2020-06-21 12:14:53',
       '2020-06-21 12:15:15', '2020-06-21 12:15:17', '2020-06-21 12:15:37',
       '2020-06-21 12:15:44', '2020-06-21 12:15:50', '2020-06-21 12:16:10',
       '2020-06-21 12:16:11',
       ...
       '2020-07-13 00:09:00', '2020-07-13 00:09:08', '2020-07-13 00:10:02',
       '2020-07-13 00:10:11', '2020-07-13 00:11:08', '2020-07-13 00:11:19',
       '2020-07-13 00:12:23', '2020-07-13 00:14:14', '2020-07-13 00:14:56',
       '2020-07-13 00:15:17'],
      dtype='object', length=61058)

In [ ]:
df['amt'],amt_name=pd.factorize(data['amt'])
print(amt_name)

Index([   2.86,   29.84,   41.28,   60.05,    3.19,   19.55,  133.93,   10.37,
          4.37,   66.54,
       ...
       1111.35,  965.25, 2017.65,  231.52,  260.44,  1031.9,   190.3,  113.13,
         169.0,  107.56],
      dtype='float64', length=17503)

In [ ]:
df['is_fraud'],fraud_name=pd.factorize(data['is_fraud'])
print(fraud_name)

Index([0.0, 1.0], dtype='float64')

In [ ]:
df['job'].unique()

array(['Mechanical engineer', 'Sales professional, IT',
       'Librarian, public', 'Set designer', 'Furniture designer',
       'Psychotherapist', 'Therapist, occupational',
       'Development worker, international aid', 'Advice worker',
       'Barrister', 'Pensions consultant', 'Freight forwarder',
       'Paramedic', 'Building surveyor', 'Materials engineer',
       'Commercial horticulturist', 'Town planner',
       'Radiographer, therapeutic', 'Surveyor, rural practice',
       'Energy manager', 'Prison officer',
       'Museum/gallery exhibitions officer', 'Media planner',
       'Seismic interpreter', 'Learning disability nurse',
       'Buyer, industrial', 'Scientific laboratory technician',
       'Counselling psychologist', 'Scientist, biomedical',
       'Audiological scientist', 'Stage manager',
       'Leisure centre manager', 'Community pharmacist', 'Risk analyst',
       'Clinical research associate', 'Librarian, academic',
       'Editor, magazine features', 'Ceramics designer', 'Musician',
       'Designer, furniture', 'Exhibition designer',
       'Engineer, automotive', 'Film/video editor', 'Web designer',
       'Environmental consultant', 'Production assistant, television',
       'Education officer, community',
       'Senior tax professional/tax inspector', 'Investment analyst',
       'Loss adjuster, chartered', 'Scientist, audiological',
       'Tax inspector', 'Primary school teacher',
       'Agricultural consultant', 'Geochemist', 'Geneticist, molecular',
       'Medical sales representative', 'Petroleum engineer',
       'Advertising account planner', 'Travel agency manager',
       'Music therapist', 'Neurosurgeon', 'Further education lecturer',
       'Therapist, sports', 'Operational researcher', 'Site engineer',
       'Communications engineer', 'Child psychotherapist',
       'Engineer, land', 'Dealer', 'Amenity horticulturist',
       'Electronics engineer', 'Research officer, political party',
       'Accounting technician', 'Licensed conveyancer',
       'Programmer, multimedia', 'Chief Financial Officer',
       'Health promotion specialist', 'Field seismologist', 'Chiropodist',
       'Special effects artist', 'Designer, ceramics/pottery',
       'Systems developer', 'Biomedical scientist',
       'Geophysicist/field seismologist', 'Electrical engineer',
       'Equities trader', 'Energy engineer', 'Police officer',
       'Music tutor', "Nurse, children's", 'Jewellery designer',
       'Therapist, art', 'Archivist', 'Production manager',
       'Farm manager', 'Editor, film/video', 'Engineer, production',
       'Journalist, newspaper', 'Drilling engineer',
       'Psychotherapist, child',
       'Programme researcher, broadcasting/film/video', 'Contractor',
       'Sub', 'Broadcast engineer', 'Animal nutritionist',
       'Intelligence analyst', 'Engineer, electronics',
       'Historic buildings inspector/conservation officer', 'Optometrist',
       'Firefighter', 'Copywriter, advertising', 'Designer, jewellery',
       'Scientist, physiological', 'Financial adviser',
       'Early years teacher', 'Insurance broker', 'Broadcast presenter',
       'Clothing/textile technologist', 'Probation officer',
       'Forensic psychologist', 'Telecommunications researcher',
       'Teacher, early years/pre',
       'Conservation officer, historic buildings',
       'Educational psychologist', 'Rural practice surveyor',
       'Patent attorney', 'Futures trader', 'Hospital doctor',
       'Chief Executive Officer', 'Chartered public finance accountant',
       'Charity fundraiser', 'Information systems manager',
       'Environmental manager', 'Designer, exhibition/display',
       'Retail banker', 'English as a second language teacher',
       'Building services engineer', 'Buyer, retail',
       'Surveyor, land/geomatics', 'Conservator, furniture',
       'Exhibitions officer, museum/gallery',
       'Accountant, chartered public finance', 'Secretary/administrator',
       'Production assistant, radio', 'Water engineer',
       'Insurance risk surveyor', 'Optician, dispensing',
       'Fisheries officer', 'Social research officer, government',
       'Curator', 'Applications developer', 'Chartered accountant',
       'Comptroller', 'Land', 'Control and instrumentation engineer',
       'Community education officer', 'Osteopath', 'Surgeon',
       'Sales executive', 'Lecturer, higher education',
       'Public relations account executive', 'Transport planner',
       'Investment banker, corporate', 'Camera operator',
       'Land/geomatics surveyor', 'Engineer, mining',
       'Armed forces training and education officer',
       'Manufacturing engineer', 'Technical brewer', 'Warden/ranger',
       'Radio broadcast assistant', 'Trade mark attorney', 'Metallurgist',
       'Heritage manager', 'Podiatrist', 'Counsellor', 'Gaffer',
       'Exercise physiologist', 'Engineer, technical sales',
       'Toxicologist', 'Magazine features editor', 'Lexicographer',
       'Editor, commissioning', 'Phytotherapist',
       'Careers information officer', 'Tax adviser',
       'Advertising copywriter', 'Occupational hygienist',
       'Accountant, chartered certified', 'Press photographer',
       'Wellsite geologist', 'Animator', 'Secondary school teacher',
       'Race relations officer', 'Tourism officer', 'Biomedical engineer',
       'Lecturer, further education', 'Public house manager',
       'Administrator', 'Minerals surveyor',
       'Scientist, clinical (histocompatibility and immunogenetics)',
       'Administrator, education', 'Market researcher',
       'Chief Operating Officer', 'Media buyer',
       'Armed forces logistics/support/administrative officer',
       'Civil engineer, contracting', 'Network engineer',
       'Engineer, drilling', 'Multimedia programmer',
       'Scientist, research (physical sciences)',
       'Special educational needs teacher', 'Geoscientist',
       'Psychologist, forensic', 'Horticulturist, commercial',
       'Furniture conservator/restorer', 'Chartered loss adjuster',
       'Tree surgeon', 'Scientist, marine',
       'Product/process development scientist', 'Financial trader',
       'Radio producer', 'Mining engineer',
       'Training and development officer', 'Chief Strategy Officer',
       'Theme park manager', 'Physiological scientist', 'Pathologist',
       'Art therapist', 'Teacher, special educational needs',
       'Television floor manager', 'Retail merchandiser',
       'Corporate investment banker', 'Pilot, airline', 'Statistician',
       'Public librarian', 'Insurance underwriter',
       'Teacher, English as a foreign language', 'Physiotherapist',
       'Teacher, adult education', 'Operations geologist',
       'Environmental education officer', 'IT trainer',
       'Research officer, trade union', 'Animal technologist',
       'Air cabin crew', 'Designer, industrial/product',
       'Engineer, civil (contracting)', "Politician's assistant",
       'Conservator, museum/gallery', 'Soil scientist', 'Arboriculturist',
       'Sports development officer', 'Television/film/video producer',
       "Barrister's clerk", 'Engineer, communications', 'Copy',
       'Water quality scientist', 'Immunologist',
       'Database administrator', 'Producer, radio', 'Cartographer',
       'Health physicist', 'Private music teacher', 'Social researcher',
       'Pension scheme manager', 'Psychologist, clinical',
       'Building control surveyor', 'Designer, textile', 'Barista',
       'Claims inspector/assessor', 'Systems analyst',
       'Structural engineer', 'Archaeologist',
       'Psychologist, counselling', 'Cytogeneticist', 'Health visitor',
       'Emergency planning/management officer',
       'Scientist, research (maths)', 'Herbalist',
       'Tourist information centre manager', 'Landscape architect',
       'Paediatric nurse', 'Video editor', 'Quantity surveyor',
       'Geologist, engineering', 'Therapist, drama', 'Doctor, hospital',
       'Hydrographic surveyor', 'Glass blower/designer',
       'Therapist, horticultural', 'Make', 'Physicist, medical',
       'Community arts worker', 'Embryologist, clinical', 'Bookseller',
       'Facilities manager', 'Theatre manager',
       'Dance movement psychotherapist', 'Scientist, research (medical)',
       'Commercial/residential surveyor',
       'Administrator, local government', 'Development worker, community',
       'Higher education careers adviser', 'Location manager',
       'General practice doctor', 'Art gallery manager',
       'Pharmacist, hospital', 'Teaching laboratory technician',
       'Chemical engineer', 'Geologist, wellsite',
       'Presenter, broadcasting', 'Community development worker',
       'Immigration officer', 'Chief Technology Officer',
       'Engineer, biomedical', 'Logistics and distribution manager',
       'Academic librarian', 'Commissioning editor',
       'Research scientist (physical sciences)',
       'Teacher, secondary school', 'Engineer, agricultural',
       'Naval architect', 'Clinical biochemist',
       'Restaurant manager, fast food', 'Data scientist',
       'Theatre director', 'Radiographer, diagnostic', 'Interpreter',
       'Psychiatric nurse', 'Research scientist (life sciences)',
       'Learning mentor', 'Lawyer',
       'Outdoor activities/education manager', 'Human resources officer',
       'Trading standards officer', 'Press sub',
       'Regulatory affairs officer', 'Pharmacist, community',
       'Engineering geologist', 'Engineer, control and instrumentation',
       'Horticultural therapist', 'Maintenance engineer',
       'Producer, television/film/video', 'Analytical chemist',
       'Surveyor, minerals', 'Hydrologist',
       'Manufacturing systems engineer', 'Dispensing optician',
       'Product designer', 'Architect', 'Education officer, museum',
       'Company secretary', 'Television production assistant',
       'Science writer', 'Quarry manager', 'Fitness centre manager',
       'Mudlogger', 'Medical physicist', 'Waste management officer',
       'Occupational psychologist', 'Colour technologist', 'Fine artist',
       'Call centre manager', 'Television camera operator',
       'Sport and exercise psychologist', 'Health service manager',
       'Interior and spatial designer', 'Nutritional therapist',
       'Clinical psychologist', 'Programmer, applications',
       'Retail manager', 'Engineer, materials', 'Diagnostic radiographer',
       'Designer, interior/spatial', 'Herpetologist',
       'Museum/gallery conservator', 'Nurse, mental health',
       'Public affairs consultant', 'Management consultant',
       'Industrial/product designer', 'Airline pilot', 'Retail buyer',
       'Psychologist, sport and exercise', 'Ambulance person',
       'Equality and diversity officer',
       'Engineer, broadcasting (operations)', 'Plant breeder/geneticist',
       'Engineer, maintenance', 'Chemist, analytical',
       'Chief Marketing Officer', 'Visual merchandiser',
       'Planning and development surveyor', 'Illustrator',
       'Merchandiser, retail', 'Psychiatrist', 'Mental health nurse',
       'Orthoptist', 'Magazine journalist', 'Doctor, general practice',
       'Product manager', 'Advertising account executive',
       'Surveyor, mining', 'Pharmacologist', 'Medical secretary',
       'Aid worker', 'Cabin crew', 'Nature conservation officer',
       'Public relations officer', 'Insurance claims handler',
       'Investment banker, operational',
       'Administrator, charities/voluntary organisations',
       'Oceanographer', 'Therapist, music', 'Local government officer',
       'Arts development officer', 'Biochemist, clinical',
       'Civil Service administrator', 'Clinical cytogeneticist', 'Writer',
       'Garment/textile technologist', 'Research scientist (maths)',
       'Museum education officer', 'Teacher, primary school',
       'Designer, multimedia', 'Textile designer',
       'Civil Service fast streamer', 'Environmental health practitioner',
       'Health and safety adviser', 'Designer, television/film set',
       'Associate Professor',
       'Chartered legal executive (England and Wales)',
       'Purchasing manager', 'Surveyor, hydrographic',
       'Hospital pharmacist', 'Research scientist (medical)',
       'Engineer, structural', 'Field trials officer',
       'Engineer, building services', 'Acupuncturist', 'Chief of Staff',
       'Records manager', 'Catering manager', 'Event organiser',
       'Engineer, petroleum', 'Production engineer',
       'Education administrator', 'IT consultant',
       'Horticultural consultant', 'Ecologist', 'Engineer, aeronautical',
       'Volunteer coordinator', 'Air broker',
       'Engineer, civil (consulting)', 'Estate manager/land agent',
       'Aeronautical engineer', 'Engineer, manufacturing',
       'Architectural technologist', 'Marketing executive',
       'Hotel manager', 'Tour manager', 'Professor Emeritus',
       'Oncologist', 'TEFL teacher', 'Economist',
       'English as a foreign language teacher', 'Hydrogeologist',
       'Medical technical officer', 'Charity officer',
       'Administrator, arts', 'Occupational therapist',
       'Solicitor, Scotland', 'Sports administrator', 'Artist',
       'Engineer, water', nan], dtype=object)

In [ ]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [ ]:
X = df.drop('is_fraud', axis=1)  # Assuming 'is_fraud' is the target variable
y = df['is_fraud']

In [ ]:
from sklearn import tree, metrics

In [ ]:

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score


iris = load_iris()
X = iris.data
y = iris.target


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

dt_classifier = DecisionTreeClassifier()

dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9777777777777777